### ISSUE TITLE
Where can I get the data.ini file. i can't find that file

### ISSUE THREAD

**Issue by jhs512** [vthibault/roBrowser#130]
i've installed the official client.

but there was no data.ini

**Comment by vthibault** [comment]
In official client there is no data.ini files, the GRFs files are listed directly on the executable and you should be able to get it by searching ".grf" in the hex.

Note : it's hard to run robrowser on an official client as you have to know the packetver, and possibly add all "custom" things only implemented on the server (it can be a security system as packet encryption).

It's not added directly on robrowser because it's server dependent (too much different code from one to another and a pain to ass to maintain) also because connecting a third party tool to an official server can lead to legal issue ;)
